// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU9FEh2NGE8ydAhMR5CXG_B13b2Mb3dC4',
    appId: '1:17234456144:web:75e8ab68fbe50b79b2ab55',
    messagingSenderId: '17234456144',
    projectId: 'mili-5beac',
    authDomain: 'mili-5beac.firebaseapp.com',
    databaseURL: 'https://mili-5beac.firebaseio.com',
    storageBucket: 'mili-5beac.appspot.com',
    measurementId: 'G-ZSLDM46LER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2-ERQimj6DL21ZVpnhPz-Yz7wo4inpDo',
    appId: '1:17234456144:android:9d571d706a825b12',
    messagingSenderId: '17234456144',
    projectId: 'mili-5beac',
    databaseURL: 'https://mili-5beac.firebaseio.com',
    storageBucket: 'mili-5beac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxEXN4xI_J2DssTMI9zo7Gv6fqhVhytEc',
    appId: '1:17234456144:ios:2c2227b3182527e9b2ab55',
    messagingSenderId: '17234456144',
    projectId: 'mili-5beac',
    databaseURL: 'https://mili-5beac.firebaseio.com',
    storageBucket: 'mili-5beac.appspot.com',
    androidClientId: '17234456144-0q55eurclpiq3qvm74hvbjjm1r5upmeg.apps.googleusercontent.com',
    iosClientId: '17234456144-brpj4rc1l8093of0g18n0mk0nhmb2oi7.apps.googleusercontent.com',
    iosBundleId: 'dev.flutter.bookstore',
  );
}
